version: '3.8'

services:
  # Container Database
  db:
    image: postgres:latest
    container_name: telkomsel_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: telkomsel_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # Container pgAdmin (Opsional: Untuk lihat isi database lewat browser)
  pgadmin:
    image: dpage/pgadmin4
    container_name: telkomsel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: