export const CITY_REGION_MAP = {
  // --- SUMATERA ---
  'BANDA ACEH': 'ACEH', 'ACEH': 'ACEH', 'NAD': 'ACEH', 'LHOKSEUMAWE': 'ACEH', 'MEULABOH': 'ACEH', 'SABANG': 'ACEH', 'LANGSA': 'ACEH',
  'MEDAN': 'SUMATERA UTARA', 'BINJAI': 'SUMATERA UTARA', 'PEMATANGSIANTAR': 'SUMATERA UTARA', 'TEBING TINGGI': 'SUMATERA UTARA', 'SIBOLGA': 'SUMATERA UTARA', 'DELI SERDANG': 'SUMATERA UTARA', 'SUMUT': 'SUMATERA UTARA', 'SUMBAGUT': 'SUMATERA UTARA',
  'PADANG': 'SUMATERA BARAT', 'BUKITTINGGI': 'SUMATERA BARAT', 'PAYAKUMBUH': 'SUMATERA BARAT', 'PARIAMAN': 'SUMATERA BARAT', 'SUMBAR': 'SUMATERA BARAT',
  'PEKANBARU': 'RIAU', 'DUMAI': 'RIAU', 'RIAU': 'RIAU', 'SUMBAGTENG': 'RIAU',
  'BATAM': 'KEPULAUAN RIAU', 'TANJUNG PINANG': 'KEPULAUAN RIAU', 'BINTAN': 'KEPULAUAN RIAU', 'KEPRI': 'KEPULAUAN RIAU',
  'JAMBI': 'JAMBI', 'SUNGAI PENUH': 'JAMBI',
  'BENGKULU': 'BENGKULU',
  'PALEMBANG': 'SUMATERA SELATAN', 'LUBUKLINGGAU': 'SUMATERA SELATAN', 'PRABUMULIH': 'SUMATERA SELATAN', 'PAGAR ALAM': 'SUMATERA SELATAN', 'SUMSEL': 'SUMATERA SELATAN', 'SUMBAGSEL': 'SUMATERA SELATAN',
  'PANGKAL PINANG': 'KEPULAUAN BANGKA BELITUNG', 'BABEL': 'KEPULAUAN BANGKA BELITUNG', 'BANGKA': 'KEPULAUAN BANGKA BELITUNG', 'BELITUNG': 'KEPULAUAN BANGKA BELITUNG',
  'BANDAR LAMPUNG': 'LAMPUNG', 'METRO': 'LAMPUNG', 'LAMPUNG': 'LAMPUNG',

  // --- JAWA ---
  'JAKARTA': 'DKI JAKARTA', 'DKI': 'DKI JAKARTA', 'JKT': 'DKI JAKARTA', 'JABOTABEK': 'DKI JAKARTA', 'SERIBU': 'DKI JAKARTA',
  'BANDUNG': 'JAWA BARAT', 'BEKASI': 'JAWA BARAT', 'DEPOK': 'JAWA BARAT', 'BOGOR': 'JAWA BARAT', 'TASIKMALAYA': 'JAWA BARAT', 'CIMAHI': 'JAWA BARAT', 'SUKABUMI': 'JAWA BARAT', 'CIREBON': 'JAWA BARAT', 'KARAWANG': 'JAWA BARAT', 'JABAR': 'JAWA BARAT',
  'SERANG': 'BANTEN', 'TANGERANG': 'BANTEN', 'CILEGON': 'BANTEN', 'BANTEN': 'BANTEN',
  'SEMARANG': 'JAWA TENGAH', 'SURAKARTA': 'JAWA TENGAH', 'SOLO': 'JAWA TENGAH', 'MAGELANG': 'JAWA TENGAH', 'PEKALONGAN': 'JAWA TENGAH', 'SALATIGA': 'JAWA TENGAH', 'TEGAL': 'JAWA TENGAH', 'JATENG': 'JAWA TENGAH',
  'YOGYAKARTA': 'DAERAH ISTIMEWA YOGYAKARTA', 'DIY': 'DAERAH ISTIMEWA YOGYAKARTA', 'JOGJA': 'DAERAH ISTIMEWA YOGYAKARTA', 'SLEMAN': 'DAERAH ISTIMEWA YOGYAKARTA', 'BANTUL': 'DAERAH ISTIMEWA YOGYAKARTA',
  'SURABAYA': 'JAWA TIMUR', 'MALANG': 'JAWA TIMUR', 'KEDIRI': 'JAWA TIMUR', 'MADIUN': 'JAWA TIMUR', 'BLITAR': 'JAWA TIMUR', 'PASURUAN': 'JAWA TIMUR', 'PROBOLINGGO': 'JAWA TIMUR', 'BATU': 'JAWA TIMUR', 'SIDOARJO': 'JAWA TIMUR', 'GRESIK': 'JAWA TIMUR', 'JATIM': 'JAWA TIMUR',

  // --- KALIMANTAN ---
  'PONTIANAK': 'KALIMANTAN BARAT', 'SINGKAWANG': 'KALIMANTAN BARAT', 'KALBAR': 'KALIMANTAN BARAT',
  'PALANGKARAYA': 'KALIMANTAN TENGAH', 'KALTENG': 'KALIMANTAN TENGAH',
  'BANJARMASIN': 'KALIMANTAN SELATAN', 'BANJARBARU': 'KALIMANTAN SELATAN', 'KALSEL': 'KALIMANTAN SELATAN',
  'SAMARINDA': 'KALIMANTAN TIMUR', 'BALIKPAPAN': 'KALIMANTAN TIMUR', 'BONTANG': 'KALIMANTAN TIMUR', 'KALTIM': 'KALIMANTAN TIMUR',
  'TANJUNG SELOR': 'KALIMANTAN UTARA', 'TARAKAN': 'KALIMANTAN UTARA', 'KALTARA': 'KALIMANTAN UTARA', 'BANJARBARU': 'KALIMANTAN SELATAN',

  // --- SULAWESI ---
  'MANADO': 'SULAWESI UTARA', 'BITUNG': 'SULAWESI UTARA', 'TOMOHON': 'SULAWESI UTARA', 'SULUT': 'SULAWESI UTARA',
  'GORONTALO': 'GORONTALO',
  'PALU': 'SULAWESI TENGAH', 'SULTENG': 'SULAWESI TENGAH',
  'MAKASSAR': 'SULAWESI SELATAN', 'PAREPARE': 'SULAWESI SELATAN', 'PALOPO': 'SULAWESI SELATAN', 'SULSEL': 'SULAWESI SELATAN',
  'KENDARI': 'SULAWESI TENGGARA', 'BAUBAU': 'SULAWESI TENGGARA', 'SULTRA': 'SULAWESI TENGGARA',
  'MAMUJU': 'SULAWESI BARAT', 'SULBAR': 'SULAWESI BARAT', 'TELING': 'SULAWESI UTARA',

  // --- BALI, NTB, NTT ---
  'DENPASAR': 'BALI', 'SINGARAJA': 'BALI', 'KUTA': 'BALI', 'UBUD': 'BALI', 'BALI': 'BALI', 'BALNUS': 'BALI',
  'MATARAM': 'NUSA TENGGARA BARAT', 'BIMA': 'NUSA TENGGARA BARAT', 'NTB': 'NUSA TENGGARA BARAT',
  'KUPANG': 'NUSA TENGGARA TIMUR', 'NTT': 'NUSA TENGGARA TIMUR',

  // --- MALUKU & PAPUA (38 PROVINSI) ---
  'AMBON': 'MALUKU', 'TUAL': 'MALUKU', 'MALUKU': 'MALUKU',
  'TERNATE': 'MALUKU UTARA', 'TIDORE': 'MALUKU UTARA', 'SOFIFI': 'MALUKU UTARA',
  'JAYAPURA': 'PAPUA', 'PAPUA': 'PAPUA',
  'MANOKWARI': 'PAPUA BARAT',
  'SORONG': 'PAPUA BARAT DAYA',
  'NABIRE': 'PAPUA TENGAH', 'TIMIKA': 'PAPUA TENGAH',
  'WAMENA': 'PAPUA PEGUNUNGAN', 'JAYAWIAYA': 'PAPUA PEGUNUNGAN',
  'MERAUKE': 'PAPUA SELATAN',
  'SULAMPUA': 'PAPUA', // Singkatan Regional Sulsel-Ambon-Papua

  // --- TAMBAHKAN KODE SITE TELKOMSEL DI SINI ---
  'PLG': 'SUMATERA SELATAN',
  'PLM': 'SUMATERA SELATAN',
  'MDN': 'SUMATERA UTARA',
  'BPP': 'KALIMANTAN TIMUR',
  'SBY': 'JAWA TIMUR',
  'JKT': 'DKI JAKARTA',
  'SOETTA': 'DKI JAKARTA',
  'MKS': 'SULAWESI SELATAN',
  'DPS': 'BALI',
  'BTM': 'KEPULAUAN RIAU',
  'BRN': 'BANTEN', 'BUARAN': 'BANTEN',
  'TMK': 'PAPUA TENGAH',
  'KNG': 'RIAU',
  'DGO': 'JAWA BARAT',
  'TBS': 'DKI JAKARTA', 'USCTBS': 'DKI JAKARTA',
  'GAYUNGAN': 'JAWA TIMUR', 'GYN': 'JAWA TIMUR', 'GYG': 'JAWA TIMUR',
  'HRM': 'JAWA TIMUR',
  'PENGAYOMAN': 'SULAWESI SELATAN',
  'SUD': 'SULAWESI SELATAN',
  'AHZ': 'SUMATERA UTARA',
  'DLD': 'JAWA TIMUR',
  'JPR': 'PAPUA',
  'BNA': 'ACEH',
  'PMS': 'SUMATERA UTARA',
  'PDG': 'SUMATERA BARAT',
  'JAM': 'JAMBI',
  'BENGKULU': 'BENGKULU',
  'BDL': 'LAMPUNG',
  'BSD': 'BANTEN',
  'BD': 'JAWA BARAT',
  'CIR': 'JAWA BARAT',
  'YGY': 'DAERAH ISTIMEWA YOGYAKARTA','YGY': 'JAWA TENGAH',
  'SMR': 'JAWA TENGAH',
  'SLO': 'JAWA TENGAH',
  'SBY': 'JAWA TIMUR',
  'MLG': 'JAWA TIMUR',
  'SGR': 'BALI',
  'MME': 'NUSA TENGGARA TIMUR',
  'KPG': 'NUSA TENGGARA TIMUR',
  'BJB': 'KALIMANTAN SELATAN',
  'PTK': 'KALIMANTAN BARAT',
  'BPP': 'KALIMANTAN TIMUR',
  'SMD': 'KALIMANTAN TIMUR',
  'PLK': 'KALIMANTAN TENGAH',
  'UPD': 'SULAWESI SELATAN',
  'KDI': 'SULAWESI TENGGARA',
  'MDO': 'SULAWESI UTARA',
  'PAL': 'SULAWESI TENGAH',
  'AMB': 'MALUKU',
  'SOR': 'PAPUA BARAT DAYA',
  'PKB': 'RIAU',
  'AMIR HAMZAH': 'SUMATERA UTARA',
  'SIANTAR': 'SUMATERA UTARA',
  'TB SIMATUPANG': 'DKI JAKARTA',


  'SUMBAGUT': 'SUMATERA',
  'SUMBAGTENG': 'SUMATERA',
  'SUMBAGSEL': 'SUMATERA',
  'JABODETABEK': 'DKI JAKARTA',
  'WEST JAVA': 'JAWA BARAT',
  'CENTRAL JAVA': 'JAWA TENGAH',
  'EAST JAVA': 'JAWA TIMUR',
  'BALI & NUSRA': 'BALI', 'BALNUS': 'BALI',
  'KALIMANTAN': 'KALIMANTAN',
  'SULAWESI': 'SULAWESI',
  'PUMA': 'PAPUA', // Biasanya PUMA (Papua Maluku) diarahkan ke Papua
};

export const getRegionFromCity = (cityName) => {
  if (!cityName) return 'UNKNOWN';
  
  const cleanInput = String(cityName).toUpperCase().trim();

  // 1. Prioritas Utama: Exact Match (Cek nama kota utuh)
  if (CITY_REGION_MAP[cleanInput]) {
    return CITY_REGION_MAP[cleanInput];
  }

  // 2. Prioritas Kedua: Keyword Matching (Urutkan dari keyword terpanjang agar akurat)
  const sortedKeywords = Object.keys(CITY_REGION_MAP).sort((a, b) => b.length - a.length);

  for (const keyword of sortedKeywords) {
    if (cleanInput.includes(keyword)) {
      return CITY_REGION_MAP[keyword];
    }
  }

  return 'UNKNOWN';
};